config/routes.rb
Interview::Application.routes.draw do
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  
  get "candidate" => "users#new_candidate"
  get "company" => "users#new_company_admin"
  post "create_candidate" => "users#create_candidate"
  post "create_company_admin" => "users#create_company_admin"
  
  resources :users
  resources :sessions
  resources :companies
  resources :tests

  root :to => "pages#root"
  match '/pricing' => "pages#pricing"
  match '/contact' => "pages#contact"
  match '/home' => "candidate#index"
  match '/admin' => "admin#index"
  match '/coadmin' => "coadmin#index"
  match '/hiring' => "hiring_manager#index"
  match '/recruiting' => "recruiter#index"

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :address1, :address2, :city, :state, :zip, :countryId
  
  validates_presence_of :name, :address1, :city, :state, :zip, :countryId, :on => :create
  validates_uniqueness_of :name
end

app/models/test.rb
class Test < ActiveRecord::Base
  
  attr_accessible :name, :creatorId
  validates :name, :creatorId, :presence => true
  
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :firstName, :lastName, :companyId, :email, :password, :password_confirmation, :roles
  
  validates_confirmation_of :password
  validates_presence_of :firstName, :lastName, :password, :email, :roles, :on => :create
  validates_uniqueness_of :email
  
  has_many :tests
  
  # Role IDs
  ROLE_ADMIN = 1
  ROLE_COMPANY_ADMIN = 2
  ROLE_RECRUITER = 3
  ROLE_HIRING_MANAGER = 4
  ROLE_CANDIDATE = 5

  # Role names
  ROLE_STR_ADMIN = "Admin"
  ROLE_STR_COMPANY_ADMIN = "Company admin"
  ROLE_STR_RECRUITER = "Recruiter"
  ROLE_STR_HIRING_MANAGER = "Hiring manager"
  ROLE_STR_CANDIDATE = "Candidate"

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :loginRedirect, :except => [:new, :create, :destroy,
    :new_candidate, :new_company_admin,
    :create_candidate, :create_company_admin,
    :root, :pricing, :contact]

  def loginRedirect
    if not current_user
      redirect_to '/login'
    end
  end
end

app/controllers/candidate_controller.rb
class CandidateController < ApplicationController
  def index
  end

end

app/controllers/coadmin_controller.rb
class CoadminController < ApplicationController
  def index
    # Load all users
    @allUsers = User.where("companyId = :id", {:id => current_user.companyId})
  end  
end

app/controllers/hiring_manager_controller.rb
class HiringManagerController < ApplicationController
  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def root
    @title = 'Home'
    @message1 = 'Job candidates get to show their abilities, rather than their interview skills.'
    @message2 = 'Recruiters get to see true talent and hire faster, more easily and with a higher accuracy.'
    @message3 = 'Get started today!'
  end
  
  def pricing
    @title = 'Pricing'
    @message1 = 'This service will always be free for candidates.'
    @message2 = 'Recruiters pay from $500/month depending on usage.'
  end
  
  def contact
    @title = 'Contact'
    @message = 'Email address and mailing address'
  end

end

app/controllers/recruiter_controller.rb
class RecruiterController < ApplicationController
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    
    if user
      redirect_to defaultPageForRole(eval(user.roles)), :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_url, :notice => "Logged out"
  end
  
  private
  
  def defaultPageForRole(role)
    defaultPage = '/'
    minRole = role.min
    
    case minRole
      when User::ROLE_ADMIN
        defaultPage = '/admin'
      when User::ROLE_COMPANY_ADMIN
        defaultPage = '/coadmin'
      when User::ROLE_RECRUITER
        defaultPage = '/recruiting'
      when User::ROLE_HIRING_MANAGER
        defaultPage = '/hiring'
      when User::ROLE_CANDIDATE
        defaultPage = '/home'
    end
    
    return defaultPage
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @allTests = current_user.tests.all
  end

  def new
    @test = Test.new
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new_candidate
    @user = User.new
  end
  
  def new_company_admin
    @company = Company.new
    @user = User.new
  end
  
  def new
    @user = User.new
  end
  
  def create_candidate
    @user = User.new(params[:user])
    @user.roles = [User::ROLE_CANDIDATE].to_s
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

  def create_company_admin
    @company = Company.new(params[:company])
    if @company.save
      @user = User.new(params[:user])
      # Manually associate the optional company
      @user.companyId = @company.id
      @user.roles = [User::ROLE_COMPANY_ADMIN].to_s
      if @user.save
        redirect_to root_url, :notice => "Signed up!"
      else
        render :new_company_admin
      end
    else
      render :new_company_admin
    end
  end

  def create
    @user = User.new(params[:user])
    roles = []
    for role in params[:role]
      roles.push(role.to_i)
    end
    @user.roles = roles.to_s
    @user.companyId = current_user.companyId
    if @user.save
      redirect_to coadmin_path, :notice => "Account created"
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    @userRoles = eval(@user.roles)
  end
  
  def update
    # Create our Roles string
    roles = []
    for role in params[:role]
      roles.push(role.to_i)
    end
    roles = roles.to_s
    attr = {
      :firstName => params[:user][:firstName],
      :lastName => params[:user][:lastName],
      :email => params[:user][:email],
      :password => params[:user][:password],
      :password_confirmation => params[:user][:password_confirmation],
      :roles => roles
    }
    if User.find(params[:id]).update_attributes(attr)    
      redirect_to coadmin_path, :notice => "Update complete"
    else
      redirect_to coadmin_path, :notice => "Update failed"
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidate_helper.rb
module CandidateHelper
end

app/helpers/coadmin_helper.rb
module CoadminHelper
end

app/helpers/hiring_manager_helper.rb
module HiringManagerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recruiter_helper.rb
module RecruiterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<%= form_for @user, :url => { :controller => "users", :action => "create" } do |f| %>
<div class="field">
  <%= f.label :firstName %>
  <%= f.text_field :firstName %>
</div>
<div class="field">
  <%= f.label :lastName %>
  <%= f.text_field :lastName %>
</div>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>
<div class="field">
  <%= check_box_tag 'role[]', User::ROLE_ADMIN %>
  <%= label_tag User::ROLE_STR_ADMIN %>
</div>
<div class="field">
  <%= check_box_tag 'role[]', User::ROLE_COMPANY_ADMIN %>
  <%= label_tag User::ROLE_STR_COMPANY_ADMIN %>
</div>
<div class="field">
  <%= check_box_tag 'role[]', User::ROLE_RECRUITER %>
  <%= label_tag User::ROLE_STR_RECRUITER %>
</div>
<div class="field">
  <%= check_box_tag 'role[]', User::ROLE_HIRING_MANAGER %>
  <%= label_tag User::ROLE_STR_HIRING_MANAGER %>
</div>
<div class="field">
  <%= check_box_tag 'role[]', User::ROLE_CANDIDATE %>
  <%= label_tag User::ROLE_STR_CANDIDATE %>
</div>
<div class="actions"><%= f.submit %></div>
<%  end %>

app/views/users/new_candidate.html.erb
<%= form_for @user, :url => { :controller => "users", :action => "create_candidate" } do |f| %>
<div class="field">
  <%= f.label :firstName %>
  <%= f.text_field :firstName %>
</div>
<div class="field">
  <%= f.label :lastName %>
  <%= f.text_field :lastName %>
</div>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>
<div class="actions"><%= f.submit %></div>
<%  end %>

app/views/users/new_company_admin.html.erb
<% form_tag(create_company_admin_path, :method=>'post') do %>
<div style="padding:5px">
  <div class="dataEntry round">
    <div>
      Company
    </div>
    <div class="field">
      <%= label :company, :name %>
      <%= text_field :company, :name %>
    </div>
    <div class="field">
      <%= label :company, :address1 %>
      <%= text_field :company, :address1 %>
    </div>
    <div class="field">
      <%= label :company, :address2 %>
      <%= text_field :company, :address2 %>
    </div>
    <div class="field">
      <%= label :company, :city %>
      <%= text_field :company, :city %>
    </div>
    <div class="field">
      <%= label :company, :state %>
      <%= text_field :company, :state %>
    </div>
    <div class="field">
      <%= label :company, :zip %>
      <%= text_field :company, :zip %>
    </div>
    <div class="field">
      <%= label :company, :countryId %>
      <%= text_field :company, :countryId %>
    </div>
  </div>
  <div>&nbsp;</div>
  <div class="dataEntry round">
    <div>
      Company administrator
    </div>
    <div class="field">
      <%= label :user, :firstName %>
      <%= text_field :user, :firstName %>
    </div>
    <div class="field">
      <%= label :user, :lastName %>
      <%= text_field :user, :lastName %>
    </div>
    <div class="field">
      <%= label :user, :email %>
      <%= text_field :user, :email %>
    </div>
    <div class="field">
      <%= label :user, :password %>
      <%= password_field :user, :password %>
    </div>
    <div class="field">
      <%= label :user, :password_confirmation %>
      <%= password_field :user, :password_confirmation %>
    </div>
  </div>
  <div class="actions"><%= submit_tag "Sign up" %></div>
</div>
<% end %>

app/views/users/show.html.erb
<%= form_for @user, :url => { :controller => "users", :action => "update" } do |f| %>
<div class="field">
  <%= f.label :firstName %>
  <%= f.text_field :firstName %>
</div>
<div class="field">
  <%= f.label :lastName %>
  <%= f.text_field :lastName %>
</div>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>
<div class="field">
  <%= check_box_tag 'role[]', User::ROLE_ADMIN, @userRoles.include?(User::ROLE_ADMIN)?true:false %>
  <%= label_tag User::ROLE_STR_ADMIN %>
</div>
<div class="field">
  <%= check_box_tag 'role[]', User::ROLE_COMPANY_ADMIN, @userRoles.include?(User::ROLE_COMPANY_ADMIN)?true:false %>
  <%= label_tag User::ROLE_STR_COMPANY_ADMIN %>
</div>
<div class="field">
  <%= check_box_tag 'role[]', User::ROLE_RECRUITER, @userRoles.include?(User::ROLE_RECRUITER)?true:false %>
  <%= label_tag User::ROLE_STR_RECRUITER %>
</div>
<div class="field">
  <%= check_box_tag 'role[]', User::ROLE_HIRING_MANAGER, @userRoles.include?(User::ROLE_HIRING_MANAGER)?true:false %>
  <%= label_tag User::ROLE_STR_HIRING_MANAGER %>
</div>
<div class="field">
  <%= check_box_tag 'role[]', User::ROLE_CANDIDATE, @userRoles.include?(User::ROLE_CANDIDATE)?true:false %>
  <%= label_tag User::ROLE_STR_CANDIDATE %>
</div>
<div class="actions"><%= f.submit %></div>
<%  end %>