config/routes.rb
Interview::Application.routes.draw do
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  
  get "candidate" => "users#new_candidate"
  get "company" => "users#new_company_admin"
  post "create_candidate" => "users#create_candidate"
  post "create_company_admin" => "users#create_company_admin"
  
  resources :users
  resources :sessions
  resources :companies
  resources :tests

  root :to => "pages#root"
  match '/pricing' => "pages#pricing"
  match '/contact' => "pages#contact"
  match '/home' => "candidate#index"
  match '/admin' => "admin#index"
  match '/coadmin' => "coadmin#index"
  match '/hiring' => "hiring_manager#index"
  match '/recruiting' => "recruiter#index"

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :address1, :address2, :city, :state, :zip, :countryId
  
  validates_presence_of :name, :address1, :city, :state, :zip, :countryId, :on => :create
  validates_uniqueness_of :name
end

app/models/test.rb
class Test < ActiveRecord::Base
  
  attr_accessible :name, :creatorId
  validates :name, :creatorId, :presence => true
  
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :firstName, :lastName, :companyId, :email, :password, :password_confirmation, :roles
  
  validates_confirmation_of :password
  validates_presence_of :firstName, :lastName, :password, :email, :roles, :on => :create
  validates_uniqueness_of :email
  
  has_many :tests
  
  # Role IDs
  ROLE_ADMIN = 1
  ROLE_COMPANY_ADMIN = 2
  ROLE_RECRUITER = 3
  ROLE_HIRING_MANAGER = 4
  ROLE_CANDIDATE = 5

  # Role names
  ROLE_STR_ADMIN = "Admin"
  ROLE_STR_COMPANY_ADMIN = "Company admin"
  ROLE_STR_RECRUITER = "Recruiter"
  ROLE_STR_HIRING_MANAGER = "Hiring manager"
  ROLE_STR_CANDIDATE = "Candidate"

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

end

app/controllers/candidate_controller.rb
class CandidateController < ApplicationController
  def index
  end

end

app/controllers/coadmin_controller.rb
class CoadminController < ApplicationController
  def index
    # Load all users
    @allUsers = User.where("companyId = :id", {:id => current_user.companyId})
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def root
    @title = 'Home'
    @message1 = 'Job candidates get to show their abilities, rather than their interview skills.'
    @message2 = 'Recruiters get to see true talent and hire faster, more easily and with a higher accuracy.'
    @message3 = 'Get started today!'
  end
  
  def pricing
    @title = 'Pricing'
    @message1 = 'This service will always be free for candidates.'
    @message2 = 'Recruiters pay from $500/month depending on usage.'
  end
  
  def contact
    @title = 'Contact'
    @message = 'Email address and mailing address'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    
    if user
      redirect_to defaultPageForRole(eval(user.roles)), :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_url, :notice => "Logged out"
  end
  
  private
  
  def defaultPageForRole(role)
    defaultPage = '/'
    minRole = role.min
    
    case minRole
      when User::ROLE_ADMIN
        defaultPage = '/admin'
      when User::ROLE_COMPANY_ADMIN
        defaultPage = '/coadmin'
      when User::ROLE_RECRUITER
        defaultPage = '/recruiting'
      when User::ROLE_HIRING_MANAGER
        defaultPage = '/hiring'
      when User::ROLE_CANDIDATE
        defaultPage = '/home'
    end
    
    return defaultPage
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @allTests = current_user.tests.all
  end

  def new
    @test = Test.new
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new_candidate
    @user = User.new
  end
  
  def new_company_admin
    @company = Company.new
    @user = User.new
  end
  
  def new
    @user = User.new
  end
  
  def create_candidate
    @user = User.new(params[:user])
    @user.roles = [User::ROLE_CANDIDATE].to_s
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

  def create_company_admin
    @company = Company.new(params[:company])
    if @company.save
      @user = User.new(params[:user])
      # Manually associate the optional company
      @user.companyId = @company.id
      @user.roles = [User::ROLE_COMPANY_ADMIN].to_s
      if @user.save
        redirect_to root_url, :notice => "Signed up!"
      else
        render :new_company_admin
      end
    else
      render :new_company_admin
    end
  end

  def create
    @user = User.new(params[:user])
    roles = []
    for role in params[:role]
      roles.push(role.to_i)
    end
    @user.roles = roles.to_s
    @user.companyId = current_user.companyId
    if @user.save
      redirect_to coadmin_path, :notice => "Account created"
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    @userRoles = eval(@user.roles)
  end
  
  def update
    # Create our Roles string
    roles = []
    for role in params[:role]
      roles.push(role.to_i)
    end
    roles = roles.to_s
    attr = {
      :firstName => params[:user][:firstName],
      :lastName => params[:user][:lastName],
      :email => params[:user][:email],
      :password => params[:user][:password],
      :password_confirmation => params[:user][:password_confirmation],
      :roles => roles
    }
    if User.find(params[:id]).update_attributes(attr)    
      redirect_to coadmin_path, :notice => "Update complete"
    else
      redirect_to coadmin_path, :notice => "Update failed"
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidate_helper.rb
module CandidateHelper
end

app/helpers/coadmin_helper.rb
module CoadminHelper
end

app/helpers/hiring_manager_helper.rb
module HiringManagerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recruiter_helper.rb
module RecruiterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="footer round">
  <span class="copytext">Copyright &copy; 2011 screen.me</span>
</div>

app/views/layouts/_header.html.erb
<div class="header round">
  <div class="logo">
    <span class="headertext">Interview filter</span>
  </div>
  <div class="welcome">
    <% if current_user %>
      <span>Welcome <%= current_user.firstName %></span>
    <% end %>
  </div>
</div>
<div class="navigation round">
  <ul>
    <%
    if current_user
        for role in eval(current_user.roles)
          case role
            when User::ROLE_ADMIN
            %>
            <li><%= link_to User::ROLE_STR_ADMIN, admin_path %></li>
            <%
            when User::ROLE_COMPANY_ADMIN
            %>
            <li><%= link_to User::ROLE_STR_COMPANY_ADMIN, coadmin_path %></li>
            <%
            when User::ROLE_RECRUITER
            %>
            <li><%= link_to User::ROLE_STR_RECRUITER, recruiting_path %></li>
            <%
            when User::ROLE_HIRING_MANAGER
            %>
            <li><%= link_to User::ROLE_STR_HIRING_MANAGER, hiring_path %></li>
            <%
            when User::ROLE_CANDIDATE
            %>
            <li><%= link_to User::ROLE_STR_CANDIDATE, home_path %></li>
            <%
            else
              puts "Error : unknown Role"  
          end
        end
        %>
        <li><%= link_to "Logout", :logout %></li>
        <%
    else %>
        <li class='current'><%= link_to "Home", root_path %></li>
        <li><%= link_to "Pricing", pricing_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Login", login_path %></li>
        <%
    end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
    <div class="container">
      <%= render 'layouts/header'%>
      <div class="content round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %> "><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/pages/contact.html.erb
<div><%= @message %></div>

app/views/pages/pricing.html.erb
<div><%= @message1 %></div>
<div><%= @message2 %></div>

app/views/pages/root.html.erb
<div><%= @message1 %></div>
<div><%= @message2 %></div>
<div><%= @message3 %></div>
<div class="userChoice">
  <span class="userSelect round">
    <span class="candidate"><%= link_to "I'm a candidate", candidate_path %></span>
  </span>
  <span>&nbsp;</span>
  <span class="userSelect round">
    <span class="company"><%= link_to "I'm a recruiter", company_path %></span>
  </span>
</div>